version: 0.0
os: linux

permissions:
  - object: /home/ec2-user/
    owner: ec2-user
    group: ec2-user

files:
  - source: ./target/
    destination: /home/ec2-user/webservice
  - source: ./cloudwatch-config.json
    destination: /opt/aws/amazon-cloudwatch-agent/

hooks:
  ApplicationStop:
    - location: ./codedeploy/applicationStop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: ./codedeploy/beforeInstall.sh
      timeout: 1200
      runas: ec2-user
  AfterInstall:
    - location: ./codedeploy/afterInstall.sh
      timeout: 400
      runas: ec2-user
  ApplicationStart:
    - location: ./codedeploy/applicationStart.sh
      timeout: 300
      runas: ec2-user